
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Nov 04 10:35:55 CST 2025
//----------------------------------------------------

package Act4;

import java_cup.runtime.*;
import java.io.*;
import java.util.ArrayList;
import java.util.List;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Tue Nov 04 10:35:55 CST 2025
  */
public class Sintactico extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintactico() {super();}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\126\000\002\002\004\000\002\010\003\000\002\010" +
    "\004\000\002\011\003\000\002\011\003\000\002\011\003" +
    "\000\002\011\003\000\002\011\003\000\002\011\003\000" +
    "\002\011\004\000\002\011\004\000\002\011\006\000\002" +
    "\011\003\000\002\022\005\000\002\002\003\000\002\002" +
    "\003\000\002\002\003\000\002\002\003\000\002\002\003" +
    "\000\002\002\003\000\002\002\003\000\002\002\003\000" +
    "\002\002\003\000\002\002\003\000\002\002\003\000\002" +
    "\023\004\000\002\012\004\000\002\006\003\000\002\006" +
    "\005\000\002\007\003\000\002\007\005\000\002\003\005" +
    "\000\002\003\005\000\002\003\005\000\002\003\005\000" +
    "\002\003\005\000\002\003\005\000\002\003\005\000\002" +
    "\003\005\000\002\003\003\000\002\005\005\000\002\005" +
    "\005\000\002\005\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\004\003\000" +
    "\002\004\003\000\002\004\005\000\002\036\002\000\002" +
    "\015\012\000\002\037\002\000\002\016\012\000\002\040" +
    "\002\000\002\041\002\000\002\042\002\000\002\017\016" +
    "\000\002\024\003\000\002\024\003\000\002\024\002\000" +
    "\002\025\003\000\002\025\002\000\002\026\003\000\002" +
    "\026\002\000\002\043\002\000\002\020\016\000\002\044" +
    "\002\000\002\021\012\000\002\027\003\000\002\027\002" +
    "\000\002\030\003\000\002\030\004\000\002\031\004\000" +
    "\002\032\003\000\002\032\004\000\002\033\005\000\002" +
    "\033\004\000\002\045\002\000\002\013\013\000\002\034" +
    "\003\000\002\034\002\000\002\014\004\000\002\014\006" +
    "\000\002\035\003\000\002\035\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\233\000\046\004\035\005\011\006\010\007\013\010" +
    "\041\011\026\012\006\013\005\016\031\017\024\023\037" +
    "\024\016\026\015\031\012\032\023\033\036\036\030\123" +
    "\032\001\002\000\056\002\ufff9\004\ufff9\005\ufff9\006\ufff9" +
    "\007\ufff9\010\ufff9\011\ufff9\012\ufff9\013\ufff9\016\ufff9\017" +
    "\ufff9\023\ufff9\024\ufff9\026\ufff9\027\ufff9\030\ufff9\031\ufff9" +
    "\032\ufff9\033\ufff9\036\ufff9\112\ufff9\123\ufff9\001\002\000" +
    "\004\123\uffed\001\002\000\004\123\ufff3\001\002\000\050" +
    "\002\235\004\035\005\011\006\010\007\013\010\041\011" +
    "\026\012\006\013\005\016\031\017\024\023\037\024\016" +
    "\026\015\031\012\032\023\033\036\036\030\123\032\001" +
    "\002\000\004\123\uffee\001\002\000\004\123\uffea\001\002" +
    "\000\004\113\226\001\002\000\004\123\uffec\001\002\000" +
    "\056\002\ufffd\004\ufffd\005\ufffd\006\ufffd\007\ufffd\010\ufffd" +
    "\011\ufffd\012\ufffd\013\ufffd\016\ufffd\017\ufffd\023\ufffd\024" +
    "\ufffd\026\ufffd\027\ufffd\030\ufffd\031\ufffd\032\ufffd\033\ufffd" +
    "\036\ufffd\112\ufffd\123\ufffd\001\002\000\004\113\203\001" +
    "\002\000\004\113\174\001\002\000\056\002\ufffb\004\ufffb" +
    "\005\ufffb\006\ufffb\007\ufffb\010\ufffb\011\ufffb\012\ufffb\013" +
    "\ufffb\016\ufffb\017\ufffb\023\ufffb\024\ufffb\026\ufffb\027\ufffb" +
    "\030\ufffb\031\ufffb\032\ufffb\033\ufffb\036\ufffb\112\ufffb\123" +
    "\ufffb\001\002\000\004\117\173\001\002\000\004\123\154" +
    "\001\002\000\056\002\ufff5\004\ufff5\005\ufff5\006\ufff5\007" +
    "\ufff5\010\ufff5\011\ufff5\012\ufff5\013\ufff5\016\ufff5\017\ufff5" +
    "\023\ufff5\024\ufff5\026\ufff5\027\ufff5\030\ufff5\031\ufff5\032" +
    "\ufff5\033\ufff5\036\ufff5\112\ufff5\123\ufff5\001\002\000\004" +
    "\111\uffcb\001\002\000\004\123\ufff0\001\002\000\056\002" +
    "\000\004\000\005\000\006\000\007\000\010\000\011\000" +
    "\012\000\013\000\016\000\017\000\023\000\024\000\026" +
    "\000\027\000\030\000\031\000\032\000\033\000\036\000" +
    "\112\000\123\000\001\002\000\004\123\ufff2\001\002\000" +
    "\056\002\ufffa\004\ufffa\005\ufffa\006\ufffa\007\ufffa\010\ufffa" +
    "\011\ufffa\012\ufffa\013\ufffa\016\ufffa\017\ufffa\023\ufffa\024" +
    "\ufffa\026\ufffa\027\ufffa\030\ufffa\031\ufffa\032\ufffa\033\ufffa" +
    "\036\ufffa\112\ufffa\123\ufffa\001\002\000\004\117\140\001" +
    "\002\000\004\123\uffeb\001\002\000\006\077\051\113\135" +
    "\001\002\000\056\002\ufffc\004\ufffc\005\ufffc\006\ufffc\007" +
    "\ufffc\010\ufffc\011\ufffc\012\ufffc\013\ufffc\016\ufffc\017\ufffc" +
    "\023\ufffc\024\ufffc\026\ufffc\027\ufffc\030\ufffc\031\ufffc\032" +
    "\ufffc\033\ufffc\036\ufffc\112\ufffc\123\ufffc\001\002\000\004" +
    "\117\134\001\002\000\004\123\uffef\001\002\000\004\113" +
    "\uffc0\001\002\000\004\123\uffe9\001\002\000\056\002\ufffe" +
    "\004\ufffe\005\ufffe\006\ufffe\007\ufffe\010\ufffe\011\ufffe\012" +
    "\ufffe\013\ufffe\016\ufffe\017\ufffe\023\ufffe\024\ufffe\026\ufffe" +
    "\027\ufffe\030\ufffe\031\ufffe\032\ufffe\033\ufffe\036\ufffe\112" +
    "\ufffe\123\ufffe\001\002\000\004\123\ufff1\001\002\000\004" +
    "\113\043\001\002\000\034\004\035\005\011\006\010\007" +
    "\013\010\041\011\026\012\006\013\005\016\031\017\024" +
    "\023\037\117\uffc5\123\050\001\002\000\004\117\121\001" +
    "\002\000\004\117\uffc7\001\002\000\004\117\uffc6\001\002" +
    "\000\004\123\113\001\002\000\004\077\051\001\002\000" +
    "\020\064\055\065\056\066\061\067\060\070\062\113\052" +
    "\123\063\001\002\000\020\064\055\065\056\066\061\067" +
    "\060\070\062\113\052\123\063\001\002\000\034\071\uffd7" +
    "\072\uffd7\073\uffd7\074\uffd7\100\uffd7\101\uffd7\102\uffd7\103" +
    "\uffd7\104\uffd7\105\uffd7\114\uffd7\117\uffd7\120\uffd7\001\002" +
    "\000\034\071\uffda\072\uffda\073\075\074\076\100\uffda\101" +
    "\uffda\102\uffda\103\uffda\104\uffda\105\uffda\114\uffda\117\uffda" +
    "\120\uffda\001\002\000\036\071\uffd3\072\uffd3\073\uffd3\074" +
    "\uffd3\100\uffd3\101\uffd3\102\uffd3\103\uffd3\104\uffd3\105\uffd3" +
    "\114\uffd3\117\uffd3\120\uffd3\122\uffd3\001\002\000\036\071" +
    "\uffd2\072\uffd2\073\uffd2\074\uffd2\100\uffd2\101\uffd2\102\uffd2" +
    "\103\uffd2\104\uffd2\105\uffd2\114\uffd2\117\uffd2\120\uffd2\122" +
    "\uffd2\001\002\000\026\071\064\072\067\100\070\101\065" +
    "\102\072\103\066\104\073\105\071\114\ufff4\117\ufff4\001" +
    "\002\000\036\071\uffd5\072\uffd5\073\uffd5\074\uffd5\100\uffd5" +
    "\101\uffd5\102\uffd5\103\uffd5\104\uffd5\105\uffd5\114\uffd5\117" +
    "\uffd5\120\uffd5\122\uffd5\001\002\000\036\071\uffd4\072\uffd4" +
    "\073\uffd4\074\uffd4\100\uffd4\101\uffd4\102\uffd4\103\uffd4\104" +
    "\uffd4\105\uffd4\114\uffd4\117\uffd4\120\uffd4\122\uffd4\001\002" +
    "\000\036\071\uffd6\072\uffd6\073\uffd6\074\uffd6\100\uffd6\101" +
    "\uffd6\102\uffd6\103\uffd6\104\uffd6\105\uffd6\114\uffd6\117\uffd6" +
    "\120\uffd6\122\uffd6\001\002\000\036\071\uffd1\072\uffd1\073" +
    "\uffd1\074\uffd1\100\uffd1\101\uffd1\102\uffd1\103\uffd1\104\uffd1" +
    "\105\uffd1\114\uffd1\117\uffd1\120\uffd1\122\uffd1\001\002\000" +
    "\020\064\055\065\056\066\061\067\060\070\062\113\052" +
    "\123\063\001\002\000\020\064\055\065\056\066\061\067" +
    "\060\070\062\113\052\123\063\001\002\000\020\064\055" +
    "\065\056\066\061\067\060\070\062\113\052\123\063\001" +
    "\002\000\020\064\055\065\056\066\061\067\060\070\062" +
    "\113\052\123\063\001\002\000\020\064\055\065\056\066" +
    "\061\067\060\070\062\113\052\123\063\001\002\000\020" +
    "\064\055\065\056\066\061\067\060\070\062\113\052\123" +
    "\063\001\002\000\020\064\055\065\056\066\061\067\060" +
    "\070\062\113\052\123\063\001\002\000\020\064\055\065" +
    "\056\066\061\067\060\070\062\113\052\123\063\001\002" +
    "\000\034\071\uffdc\072\uffdc\073\075\074\076\100\uffdc\101" +
    "\uffdc\102\uffdc\103\uffdc\104\uffdc\105\uffdc\114\uffdc\117\uffdc" +
    "\120\uffdc\001\002\000\020\064\055\065\056\066\061\067" +
    "\060\070\062\113\052\123\063\001\002\000\020\064\055" +
    "\065\056\066\061\067\060\070\062\113\052\123\063\001" +
    "\002\000\034\071\uffd8\072\uffd8\073\uffd8\074\uffd8\100\uffd8" +
    "\101\uffd8\102\uffd8\103\uffd8\104\uffd8\105\uffd8\114\uffd8\117" +
    "\uffd8\120\uffd8\001\002\000\034\071\uffd9\072\uffd9\073\uffd9" +
    "\074\uffd9\100\uffd9\101\uffd9\102\uffd9\103\uffd9\104\uffd9\105" +
    "\uffd9\114\uffd9\117\uffd9\120\uffd9\001\002\000\034\071\uffdf" +
    "\072\uffdf\073\075\074\076\100\uffdf\101\uffdf\102\uffdf\103" +
    "\uffdf\104\uffdf\105\uffdf\114\uffdf\117\uffdf\120\uffdf\001\002" +
    "\000\034\071\uffdd\072\uffdd\073\075\074\076\100\uffdd\101" +
    "\uffdd\102\uffdd\103\uffdd\104\uffdd\105\uffdd\114\uffdd\117\uffdd" +
    "\120\uffdd\001\002\000\034\071\uffde\072\uffde\073\075\074" +
    "\076\100\uffde\101\uffde\102\uffde\103\uffde\104\uffde\105\uffde" +
    "\114\uffde\117\uffde\120\uffde\001\002\000\034\071\uffe1\072" +
    "\uffe1\073\075\074\076\100\uffe1\101\uffe1\102\uffe1\103\uffe1" +
    "\104\uffe1\105\uffe1\114\uffe1\117\uffe1\120\uffe1\001\002\000" +
    "\034\071\uffe0\072\uffe0\073\075\074\076\100\uffe0\101\uffe0" +
    "\102\uffe0\103\uffe0\104\uffe0\105\uffe0\114\uffe0\117\uffe0\120" +
    "\uffe0\001\002\000\034\071\uffdb\072\uffdb\073\075\074\076" +
    "\100\uffdb\101\uffdb\102\uffdb\103\uffdb\104\uffdb\105\uffdb\114" +
    "\uffdb\117\uffdb\120\uffdb\001\002\000\034\071\uffe2\072\uffe2" +
    "\073\075\074\076\100\uffe2\101\uffe2\102\uffe2\103\uffe2\104" +
    "\uffe2\105\uffe2\114\uffe2\117\uffe2\120\uffe2\001\002\000\024" +
    "\071\064\072\067\100\070\101\065\102\072\103\066\104" +
    "\073\105\071\114\111\001\002\000\036\071\uffd0\072\uffd0" +
    "\073\uffd0\074\uffd0\100\uffd0\101\uffd0\102\uffd0\103\uffd0\104" +
    "\uffd0\105\uffd0\114\uffd0\117\uffd0\120\uffd0\122\uffd0\001\002" +
    "\000\006\117\uffe8\120\117\001\002\000\010\077\115\117" +
    "\uffe4\120\uffe4\001\002\000\006\117\uffe6\120\uffe6\001\002" +
    "\000\020\064\055\065\056\066\061\067\060\070\062\113" +
    "\052\123\063\001\002\000\026\071\064\072\067\100\070" +
    "\101\065\102\072\103\066\104\073\105\071\117\uffe3\120" +
    "\uffe3\001\002\000\004\123\113\001\002\000\006\117\uffe5" +
    "\120\uffe5\001\002\000\022\064\055\065\056\066\061\067" +
    "\060\070\062\113\052\117\uffc3\123\063\001\002\000\024" +
    "\071\064\072\067\100\070\101\065\102\072\103\066\104" +
    "\073\105\071\117\uffc4\001\002\000\004\117\124\001\002" +
    "\000\006\114\uffc1\123\050\001\002\000\004\114\127\001" +
    "\002\000\004\114\uffc2\001\002\000\004\111\130\001\002" +
    "\000\046\004\035\005\011\006\010\007\013\010\041\011" +
    "\026\012\006\013\005\016\031\017\024\023\037\024\016" +
    "\026\015\031\012\032\023\033\036\036\030\123\032\001" +
    "\002\000\050\004\035\005\011\006\010\007\013\010\041" +
    "\011\026\012\006\013\005\016\031\017\024\023\037\024" +
    "\016\026\015\031\012\032\023\033\036\036\030\112\132" +
    "\123\032\001\002\000\056\002\uffbf\004\uffbf\005\uffbf\006" +
    "\uffbf\007\uffbf\010\uffbf\011\uffbf\012\uffbf\013\uffbf\016\uffbf" +
    "\017\uffbf\023\uffbf\024\uffbf\026\uffbf\027\uffbf\030\uffbf\031" +
    "\uffbf\032\uffbf\033\uffbf\036\uffbf\112\uffbf\123\uffbf\001\002" +
    "\000\056\002\uffff\004\uffff\005\uffff\006\uffff\007\uffff\010" +
    "\uffff\011\uffff\012\uffff\013\uffff\016\uffff\017\uffff\023\uffff" +
    "\024\uffff\026\uffff\027\uffff\030\uffff\031\uffff\032\uffff\033" +
    "\uffff\036\uffff\112\uffff\123\uffff\001\002\000\056\002\uffe7" +
    "\004\uffe7\005\uffe7\006\uffe7\007\uffe7\010\uffe7\011\uffe7\012" +
    "\uffe7\013\uffe7\016\uffe7\017\uffe7\023\uffe7\024\uffe7\026\uffe7" +
    "\027\uffe7\030\uffe7\031\uffe7\032\uffe7\033\uffe7\036\uffe7\112" +
    "\uffe7\123\uffe7\001\002\000\004\114\136\001\002\000\004" +
    "\117\137\001\002\000\056\002\ufff6\004\ufff6\005\ufff6\006" +
    "\ufff6\007\ufff6\010\ufff6\011\ufff6\012\ufff6\013\ufff6\016\ufff6" +
    "\017\ufff6\023\ufff6\024\ufff6\026\ufff6\027\ufff6\030\ufff6\031" +
    "\ufff6\032\ufff6\033\ufff6\036\ufff6\112\ufff6\123\ufff6\001\002" +
    "\000\056\002\ufff7\004\ufff7\005\ufff7\006\ufff7\007\ufff7\010" +
    "\ufff7\011\ufff7\012\ufff7\013\ufff7\016\ufff7\017\ufff7\023\ufff7" +
    "\024\ufff7\026\ufff7\027\ufff7\030\ufff7\031\ufff7\032\ufff7\033" +
    "\ufff7\036\ufff7\112\ufff7\123\ufff7\001\002\000\004\111\142" +
    "\001\002\000\046\004\035\005\011\006\010\007\013\010" +
    "\041\011\026\012\006\013\005\016\031\017\024\023\037" +
    "\024\016\026\015\031\012\032\023\033\036\036\030\123" +
    "\032\001\002\000\050\004\035\005\011\006\010\007\013" +
    "\010\041\011\026\012\006\013\005\016\031\017\024\023" +
    "\037\024\016\026\015\031\012\032\023\033\036\036\030" +
    "\112\144\123\032\001\002\000\004\031\uffca\001\002\000" +
    "\004\031\146\001\002\000\004\113\147\001\002\000\020" +
    "\064\055\065\056\066\061\067\060\070\062\113\052\123" +
    "\063\001\002\000\024\071\064\072\067\100\070\101\065" +
    "\102\072\103\066\104\073\105\071\114\151\001\002\000" +
    "\004\117\uffc9\001\002\000\004\117\153\001\002\000\056" +
    "\002\uffc8\004\uffc8\005\uffc8\006\uffc8\007\uffc8\010\uffc8\011" +
    "\uffc8\012\uffc8\013\uffc8\016\uffc8\017\uffc8\023\uffc8\024\uffc8" +
    "\026\uffc8\027\uffc8\030\uffc8\031\uffc8\032\uffc8\033\uffc8\036" +
    "\uffc8\112\uffc8\123\uffc8\001\002\000\012\077\115\113\155" +
    "\117\uffe4\120\uffe4\001\002\000\032\004\035\005\011\006" +
    "\010\007\013\010\041\011\026\012\006\013\005\016\031" +
    "\017\024\023\037\114\uffb0\001\002\000\004\114\165\001" +
    "\002\000\004\123\164\001\002\000\006\114\uffb1\120\161" +
    "\001\002\000\030\004\035\005\011\006\010\007\013\010" +
    "\041\011\026\012\006\013\005\016\031\017\024\023\037" +
    "\001\002\000\004\123\163\001\002\000\006\114\uffae\120" +
    "\uffae\001\002\000\006\114\uffaf\120\uffaf\001\002\000\004" +
    "\111\uffb3\001\002\000\004\111\167\001\002\000\050\004" +
    "\035\005\011\006\010\007\013\010\041\011\026\012\006" +
    "\013\005\016\031\017\024\023\037\024\016\026\015\031" +
    "\012\032\023\033\036\036\030\112\uffac\123\032\001\002" +
    "\000\050\004\035\005\011\006\010\007\013\010\041\011" +
    "\026\012\006\013\005\016\031\017\024\023\037\024\016" +
    "\026\015\031\012\032\023\033\036\036\030\112\uffad\123" +
    "\032\001\002\000\004\112\172\001\002\000\056\002\uffb2" +
    "\004\uffb2\005\uffb2\006\uffb2\007\uffb2\010\uffb2\011\uffb2\012" +
    "\uffb2\013\uffb2\016\uffb2\017\uffb2\023\uffb2\024\uffb2\026\uffb2" +
    "\027\uffb2\030\uffb2\031\uffb2\032\uffb2\033\uffb2\036\uffb2\112" +
    "\uffb2\123\uffb2\001\002\000\056\002\ufff8\004\ufff8\005\ufff8" +
    "\006\ufff8\007\ufff8\010\ufff8\011\ufff8\012\ufff8\013\ufff8\016" +
    "\ufff8\017\ufff8\023\ufff8\024\ufff8\026\ufff8\027\ufff8\030\ufff8" +
    "\031\ufff8\032\ufff8\033\ufff8\036\ufff8\112\ufff8\123\ufff8\001" +
    "\002\000\020\064\055\065\056\066\061\067\060\070\062" +
    "\113\052\123\063\001\002\000\024\071\064\072\067\100" +
    "\070\101\065\102\072\103\066\104\073\105\071\114\176" +
    "\001\002\000\004\111\uffcf\001\002\000\004\111\200\001" +
    "\002\000\046\004\035\005\011\006\010\007\013\010\041" +
    "\011\026\012\006\013\005\016\031\017\024\023\037\024" +
    "\016\026\015\031\012\032\023\033\036\036\030\123\032" +
    "\001\002\000\050\004\035\005\011\006\010\007\013\010" +
    "\041\011\026\012\006\013\005\016\031\017\024\023\037" +
    "\024\016\026\015\031\012\032\023\033\036\036\030\112" +
    "\202\123\032\001\002\000\056\002\uffce\004\uffce\005\uffce" +
    "\006\uffce\007\uffce\010\uffce\011\uffce\012\uffce\013\uffce\016" +
    "\uffce\017\uffce\023\uffce\024\uffce\026\uffce\027\uffce\030\uffce" +
    "\031\uffce\032\uffce\033\uffce\036\uffce\112\uffce\123\uffce\001" +
    "\002\000\020\064\055\065\056\066\061\067\060\070\062" +
    "\113\052\123\063\001\002\000\024\071\064\072\067\100" +
    "\070\101\065\102\072\103\066\104\073\105\071\114\205" +
    "\001\002\000\004\111\uffbe\001\002\000\004\111\207\001" +
    "\002\000\010\027\216\030\210\112\uffbb\001\002\000\004" +
    "\122\225\001\002\000\004\112\224\001\002\000\010\027" +
    "\216\030\210\112\uffbc\001\002\000\052\004\035\005\011" +
    "\006\010\007\013\010\041\011\026\012\006\013\005\016" +
    "\031\017\024\023\037\024\016\026\015\027\216\030\210" +
    "\031\012\032\023\033\036\036\030\123\032\001\002\000" +
    "\010\027\uffba\030\uffba\112\uffba\001\002\000\052\004\uffb7" +
    "\005\uffb7\006\uffb7\007\uffb7\010\uffb7\011\uffb7\012\uffb7\013" +
    "\uffb7\016\uffb7\017\uffb7\023\uffb7\024\uffb7\026\uffb7\027\uffb7" +
    "\030\uffb7\031\uffb7\032\uffb7\033\uffb7\036\uffb7\123\uffb7\001" +
    "\002\000\020\064\055\065\056\066\061\067\060\070\062" +
    "\113\052\123\063\001\002\000\004\122\220\001\002\000" +
    "\052\004\uffb5\005\uffb5\006\uffb5\007\uffb5\010\uffb5\011\uffb5" +
    "\012\uffb5\013\uffb5\016\uffb5\017\uffb5\023\uffb5\024\uffb5\026" +
    "\uffb5\027\uffb5\030\uffb5\031\uffb5\032\uffb5\033\uffb5\036\uffb5" +
    "\123\uffb5\001\002\000\054\004\035\005\011\006\010\007" +
    "\013\010\041\011\026\012\006\013\005\016\031\017\024" +
    "\023\037\024\016\026\015\027\uffb8\030\uffb8\031\012\032" +
    "\023\033\036\036\030\112\uffb8\123\032\001\002\000\052" +
    "\004\uffb6\005\uffb6\006\uffb6\007\uffb6\010\uffb6\011\uffb6\012" +
    "\uffb6\013\uffb6\016\uffb6\017\uffb6\023\uffb6\024\uffb6\026\uffb6" +
    "\027\uffb6\030\uffb6\031\uffb6\032\uffb6\033\uffb6\036\uffb6\123" +
    "\uffb6\001\002\000\010\027\uffb9\030\uffb9\112\uffb9\001\002" +
    "\000\056\002\uffbd\004\uffbd\005\uffbd\006\uffbd\007\uffbd\010" +
    "\uffbd\011\uffbd\012\uffbd\013\uffbd\016\uffbd\017\uffbd\023\uffbd" +
    "\024\uffbd\026\uffbd\027\uffbd\030\uffbd\031\uffbd\032\uffbd\033" +
    "\uffbd\036\uffbd\112\uffbd\123\uffbd\001\002\000\052\004\uffb4" +
    "\005\uffb4\006\uffb4\007\uffb4\010\uffb4\011\uffb4\012\uffb4\013" +
    "\uffb4\016\uffb4\017\uffb4\023\uffb4\024\uffb4\026\uffb4\027\uffb4" +
    "\030\uffb4\031\uffb4\032\uffb4\033\uffb4\036\uffb4\123\uffb4\001" +
    "\002\000\020\064\055\065\056\066\061\067\060\070\062" +
    "\113\052\123\063\001\002\000\024\071\064\072\067\100" +
    "\070\101\065\102\072\103\066\104\073\105\071\114\230" +
    "\001\002\000\004\111\uffcd\001\002\000\004\111\232\001" +
    "\002\000\046\004\035\005\011\006\010\007\013\010\041" +
    "\011\026\012\006\013\005\016\031\017\024\023\037\024" +
    "\016\026\015\031\012\032\023\033\036\036\030\123\032" +
    "\001\002\000\050\004\035\005\011\006\010\007\013\010" +
    "\041\011\026\012\006\013\005\016\031\017\024\023\037" +
    "\024\016\026\015\031\012\032\023\033\036\036\030\112" +
    "\234\123\032\001\002\000\056\002\uffcc\004\uffcc\005\uffcc" +
    "\006\uffcc\007\uffcc\010\uffcc\011\uffcc\012\uffcc\013\uffcc\016" +
    "\uffcc\017\uffcc\023\uffcc\024\uffcc\026\uffcc\027\uffcc\030\uffcc" +
    "\031\uffcc\032\uffcc\033\uffcc\036\uffcc\112\uffcc\123\uffcc\001" +
    "\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\233\000\032\002\020\010\006\011\024\012\037\013" +
    "\021\015\013\016\032\017\016\020\026\021\003\022\017" +
    "\023\033\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\030\002\020\011\132\012\037\013\021" +
    "\015\013\016\032\017\016\020\026\021\003\022\017\023" +
    "\033\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\006\111\007\113\001\001\000\002\001\001\000" +
    "\004\040\140\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\043\041\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\012\002\046\022\045\023\044\024\043\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\006\111\007\113\001\001\000\002\001\001\000" +
    "\010\003\056\004\052\005\053\001\001\000\010\003\107" +
    "\004\052\005\053\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\004\052\005\106\001\001\000\006" +
    "\004\052\005\105\001\001\000\006\004\052\005\104\001" +
    "\001\000\006\004\052\005\103\001\001\000\006\004\052" +
    "\005\102\001\001\000\006\004\052\005\101\001\001\000" +
    "\006\004\052\005\100\001\001\000\006\004\052\005\073" +
    "\001\001\000\002\001\001\000\004\004\077\001\001\000" +
    "\004\004\076\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\003\115" +
    "\004\052\005\053\001\001\000\002\001\001\000\004\007" +
    "\117\001\001\000\002\001\001\000\012\003\121\004\052" +
    "\005\053\025\122\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\022\125\026\124\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\032\002\020\010" +
    "\130\011\024\012\037\013\021\015\013\016\032\017\016" +
    "\020\026\021\003\022\017\023\033\001\001\000\030\002" +
    "\020\011\132\012\037\013\021\015\013\016\032\017\016" +
    "\020\026\021\003\022\017\023\033\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\032\002\020\010\142\011\024\012\037" +
    "\013\021\015\013\016\032\017\016\020\026\021\003\022" +
    "\017\023\033\001\001\000\030\002\020\011\132\012\037" +
    "\013\021\015\013\016\032\017\016\020\026\021\003\022" +
    "\017\023\033\001\001\000\004\041\144\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\003\147\004\052\005" +
    "\053\001\001\000\002\001\001\000\004\042\151\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\002\156\014\157\034\155\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\002\161\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\045\165\001\001\000\002\001\001\000\034\002" +
    "\020\010\167\011\024\012\037\013\021\015\013\016\032" +
    "\017\016\020\026\021\003\022\017\023\033\035\170\001" +
    "\001\000\030\002\020\011\132\012\037\013\021\015\013" +
    "\016\032\017\016\020\026\021\003\022\017\023\033\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\003\174\004\052\005\053\001\001\000\002\001" +
    "\001\000\004\036\176\001\001\000\002\001\001\000\032" +
    "\002\020\010\200\011\024\012\037\013\021\015\013\016" +
    "\032\017\016\020\026\021\003\022\017\023\033\001\001" +
    "\000\030\002\020\011\132\012\037\013\021\015\013\016" +
    "\032\017\016\020\026\021\003\022\017\023\033\001\001" +
    "\000\002\001\001\000\010\003\203\004\052\005\053\001" +
    "\001\000\002\001\001\000\004\044\205\001\001\000\002" +
    "\001\001\000\014\027\210\030\211\031\213\032\212\033" +
    "\214\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\031\222\032\212\033\214\001\001\000\034\002\020\010" +
    "\220\011\024\012\037\013\021\015\013\016\032\017\016" +
    "\020\026\021\003\022\017\023\033\033\221\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\004\216\001\001" +
    "\000\002\001\001\000\002\001\001\000\030\002\020\011" +
    "\132\012\037\013\021\015\013\016\032\017\016\020\026" +
    "\021\003\022\017\023\033\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\003\226\004\052\005\053\001\001\000\002\001\001\000" +
    "\004\037\230\001\001\000\002\001\001\000\032\002\020" +
    "\010\232\011\024\012\037\013\021\015\013\016\032\017" +
    "\016\020\026\021\003\022\017\023\033\001\001\000\030" +
    "\002\020\011\132\012\037\013\021\015\013\016\032\017" +
    "\016\020\026\021\003\022\017\023\033\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public TablaSimbolos tablaSimbolos = new TablaSimbolos();
    public List<String> erroresSemanticos = new ArrayList<>();
    public String tipoSwitchActual = null;

    public void reportarErrorSemantico(String mensaje, Symbol info) {
        String error = "Error Semantico: " + mensaje + " en la linea " + (info.left) + ", columna " + (info.right) + ".";
        if (!erroresSemanticos.contains(error)) {
            erroresSemanticos.add(error);
            System.err.println(error);
        }
    }

    public void report_fatal_error(String mensaje, Object informacion) { report_error(mensaje, informacion); }
    public void syntax_error(Symbol token_actual) {
        String mensajeError = "Error de sintaxis. ";
        if (token_actual.value != null) {
            mensajeError += "Token inesperado: '" + token_actual.value + "'.";
        }
        System.err.println(mensajeError + " Linea: " + (token_actual.left) + ", Columna: " + (token_actual.right));
    }
    public void report_error(String mensaje, Object informacion) {
        if (informacion instanceof Symbol) {
            Symbol s = ((Symbol) informacion);
            if (s.left >= 0 && s.right >= 0) {
                syntax_error(s);
                return;
            }
        }
        System.err.println(mensaje);
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintactico$actions {
  private final Sintactico parser;

  /** Constructor */
  CUP$Sintactico$actions(Sintactico parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintactico$do_action(
    int                        CUP$Sintactico$act_num,
    java_cup.runtime.lr_parser CUP$Sintactico$parser,
    java.util.Stack            CUP$Sintactico$stack,
    int                        CUP$Sintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintactico$result;

      /* select the action based on the action number */
      switch (CUP$Sintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // sentencias_opt ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencias_opt",27, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // sentencias_opt ::= sentencias 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencias_opt",27, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // parametros ::= parametros COMA tipo_dato IDENTIFICADOR 
            {
              Object RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String tipo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                Symbol id_sym = (Symbol) CUP$Sintactico$stack.peek();
                parser.tablaSimbolos.insertar(id_sym.value.toString(), tipo, id_sym.left, id_sym.right);
             
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("parametros",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // parametros ::= tipo_dato IDENTIFICADOR 
            {
              Object RESULT =null;
		int tipoleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int tiporight = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String tipo = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                Symbol id_sym = (Symbol) CUP$Sintactico$stack.peek();
                parser.tablaSimbolos.insertar(id_sym.value.toString(), tipo, id_sym.left, id_sym.right);
             
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("parametros",10, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // parametros_opt ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("parametros_opt",26, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // parametros_opt ::= parametros 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("parametros_opt",26, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // declaracion_metodo ::= tipo_dato IDENTIFICADOR PAREN_APERTURA parametros_opt PAREN_CIERRE NT$7 LLAVE_APERTURA sentencias_opt LLAVE_CIERRE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int retleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)).left;
		int retright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)).right;
		String ret = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)).value;
		
                          parser.tablaSimbolos.salirAlcance();
                      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("declaracion_metodo",9, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // NT$7 ::= 
            {
              Object RESULT =null;
		int retleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).left;
		int retright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).right;
		String ret = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;

                          Symbol symId = (Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3);
                          String nombreMetodo = symId.value.toString();

                          if (!parser.tablaSimbolos.insertar(nombreMetodo, ret, symId.left, symId.right)) {
                              parser.reportarErrorSemantico("El método '" + nombreMetodo + "' ya fue declarado", symId);
                          }

                          parser.tablaSimbolos.entrarAlcance();
                      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$7",35, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // switch_label ::= DEFAULT DOS_PUNTOS 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("switch_label",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // switch_label ::= CASE valor DOS_PUNTOS 
            {
              Object RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
                    String tipoCase = (String) v;
                    if (parser.tipoSwitchActual != null && !parser.tipoSwitchActual.equals("error_tipo") && !tipoCase.equals("error_tipo")) {
                        if (!parser.tipoSwitchActual.equals(tipoCase)) {
                            Symbol sym_case = (Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2); 
                            parser.reportarErrorSemantico("Tipo de 'case' (" + tipoCase + ") incompatible con el tipo del 'switch' (" + parser.tipoSwitchActual + ")", sym_case);
                        }
                    }
                 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("switch_label",25, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // switch_label_list ::= switch_label_list switch_label 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("switch_label_list",24, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // switch_label_list ::= switch_label 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("switch_label_list",24, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // switch_section ::= switch_label_list sentencias 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("switch_section",23, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // switch_section_list ::= switch_section_list switch_section 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("switch_section_list",22, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // switch_section_list ::= switch_section 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("switch_section_list",22, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // switch_body ::= 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("switch_body",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // switch_body ::= switch_section_list 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("switch_body",21, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // sentencia_switch ::= SWITCH PAREN_APERTURA expresion PAREN_CIERRE NT$6 LLAVE_APERTURA switch_body LLAVE_CIERRE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).value;
		
                          parser.tablaSimbolos.salirAlcance();
                          parser.tipoSwitchActual = null;
                     
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_switch",15, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // NT$6 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;

                          String tipo = (String) e;
                          if (!tipo.equals("INT") && !tipo.equals("STRING") && !tipo.equals("CHAR") && !tipo.equals("error_tipo")) {
                              Symbol sym_paren_cierre = (Symbol) CUP$Sintactico$stack.peek();
                              parser.reportarErrorSemantico("El tipo " + tipo + " no es válido para una sentencia 'switch'", sym_paren_cierre);
                              parser.tipoSwitchActual = "error_tipo";
                          } else {
                              parser.tipoSwitchActual = tipo;
                          }
                          parser.tablaSimbolos.entrarAlcance();
                     
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$6",34, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // sentencia_for ::= FOR NT$5 PAREN_APERTURA for_init_opt PUNTO_COMA for_cond_opt PUNTO_COMA for_inc_opt PAREN_CIERRE LLAVE_APERTURA sentencias LLAVE_CIERRE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-10)).value;
		int initleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)).left;
		int initright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)).right;
		Object init = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-8)).value;
		int condleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-6)).left;
		int condright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-6)).right;
		Object cond = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-6)).value;
		int incleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).left;
		int incright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).right;
		Object inc = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).value;
		
        if (cond != null && !cond.equals("BOOL") && !cond.equals("error_tipo")) {
            Symbol sym_punto_coma = (Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-6);
            parser.reportarErrorSemantico("La condición del bucle 'for' debe ser de tipo BOOL, no " + cond, sym_punto_coma);
        }
        parser.tablaSimbolos.salirAlcance();
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_for",14, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-11)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // NT$5 ::= 
            {
              Object RESULT =null;
 parser.tablaSimbolos.entrarAlcance(); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$5",33, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // for_inc_opt ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_inc_opt",20, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // for_inc_opt ::= asignacion 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = a; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_inc_opt",20, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // for_cond_opt ::= 
            {
              Object RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_cond_opt",19, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // for_cond_opt ::= expresion 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = e; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_cond_opt",19, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // for_init_opt ::= 
            {
              Object RESULT =null;
		 RESULT = null; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init_opt",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // for_init_opt ::= asignacion 
            {
              Object RESULT =null;
		int asigleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int asigright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object asig = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = asig; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init_opt",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // for_init_opt ::= for_declaracion 
            {
              Object RESULT =null;
		int declleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int declright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object decl = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = decl; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_init_opt",18, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // sentencia_do ::= DO NT$2 LLAVE_APERTURA sentencias LLAVE_CIERRE NT$3 WHILE PAREN_APERTURA expresion PAREN_CIERRE NT$4 PUNTO_COMA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_do",13, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-11)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // NT$4 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-4)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;

                 String tipo = (String) e;
                 if (!tipo.equals("BOOL") && !tipo.equals("error_tipo")) {
                      Symbol sym_paren_cierre = (Symbol) CUP$Sintactico$stack.peek();
                      parser.reportarErrorSemantico("La condición del 'do-while' debe ser de tipo BOOL, no " + tipo, sym_paren_cierre);
                 }
             
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$4",32, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // NT$3 ::= 
            {
              Object RESULT =(Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
 parser.tablaSimbolos.salirAlcance(); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$3",31, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // NT$2 ::= 
            {
              Object RESULT =null;
 parser.tablaSimbolos.entrarAlcance(); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$2",30, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // sentencia_while ::= WHILE PAREN_APERTURA expresion PAREN_CIERRE NT$1 LLAVE_APERTURA sentencias LLAVE_CIERRE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).value;
		 parser.tablaSimbolos.salirAlcance(); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_while",12, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // NT$1 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;

                      String tipo = (String) e;
                      if (!tipo.equals("BOOL") && !tipo.equals("error_tipo")) {
                          Symbol sym_paren_cierre = (Symbol) CUP$Sintactico$stack.peek();
                          parser.reportarErrorSemantico("La condición del 'while' debe ser de tipo BOOL, no " + tipo, sym_paren_cierre);
                      }
                      parser.tablaSimbolos.entrarAlcance();
                      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$1",29, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // sentencia_if ::= IF PAREN_APERTURA expresion PAREN_CIERRE NT$0 LLAVE_APERTURA sentencias LLAVE_CIERRE 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-5)).value;
		 parser.tablaSimbolos.salirAlcance(); 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia_if",11, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-7)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // NT$0 ::= 
            {
              Object RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;

                 String tipo = (String) e;
                 if (!tipo.equals("BOOL") && !tipo.equals("error_tipo")) {
                      Symbol sym_paren_cierre = (Symbol) CUP$Sintactico$stack.peek(); 
                      parser.reportarErrorSemantico("La condición del 'if' debe ser de tipo BOOL, no " + tipo, sym_paren_cierre);
                 }
                 parser.tablaSimbolos.entrarAlcance();
             
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("NT$0",28, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // valor ::= PAREN_APERTURA expresion PAREN_CIERRE 
            {
              String RESULT =null;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		 RESULT = e; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // valor ::= IDENTIFICADOR 
            {
              String RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
          Symbol id_sym = (Symbol) CUP$Sintactico$stack.peek();
          Simbolo s = parser.tablaSimbolos.buscar(id_sym.value.toString());
          if (s == null) {
              parser.reportarErrorSemantico("Identificador '" + id_sym.value + "' no ha sido declarado", id_sym);
              RESULT = "error_tipo";
          } else {
              RESULT = s.tipo;
          }
      
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // valor ::= FALSE 
            {
              String RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // valor ::= TRUE 
            {
              String RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // valor ::= VALOR_CADENA 
            {
              String RESULT =null;
		 RESULT = "STRING"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // valor ::= VALOR_FLOTANTE 
            {
              String RESULT =null;
		 RESULT = "FLOAT"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // valor ::= VALOR_ENTERO 
            {
              String RESULT =null;
		 RESULT = "INT"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("valor",2, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // termino ::= valor 
            {
              String RESULT =null;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = v; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("termino",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // termino ::= termino OPERADOR_DIVISION valor 
            {
              String RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                String tipo_t1 = (String)t1;
                String tipo_v = (String)v;
                Symbol op_symbol = (Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1);
                
                if ((tipo_t1.equals("INT") || tipo_t1.equals("FLOAT")) && (tipo_v.equals("INT") || tipo_v.equals("FLOAT"))) {
                    RESULT = "FLOAT";
                } else {
                    parser.reportarErrorSemantico("Operacion de division invalida entre los tipos " + tipo_t1 + " y " + tipo_v, op_symbol);
                    RESULT = "error_tipo";
                }
           
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("termino",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // termino ::= termino OPERADOR_MULTIPLICACION valor 
            {
              String RESULT =null;
		int t1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int t1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String t1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int vleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int vright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String v = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                String tipo_t1 = (String)t1;
                String tipo_v = (String)v;
                Symbol op_symbol = (Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1);
                
                if ((tipo_t1.equals("INT") || tipo_t1.equals("FLOAT")) && (tipo_v.equals("INT") || tipo_v.equals("FLOAT"))) {
                    RESULT = tipo_t1.equals("FLOAT") || tipo_v.equals("FLOAT") ? "FLOAT" : "INT";
                } else {
                    parser.reportarErrorSemantico("Operacion de multiplicacion invalida entre los tipos " + tipo_t1 + " y " + tipo_v, op_symbol);
                    RESULT = "error_tipo";
                }
           
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("termino",3, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // expresion ::= termino 
            {
              String RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		 RESULT = t; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // expresion ::= expresion DIFERENTE termino 
            {
              String RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // expresion ::= expresion MAYOR_IGUAL termino 
            {
              String RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // expresion ::= expresion MENOR_IGUAL termino 
            {
              String RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // expresion ::= expresion IGUAL_A termino 
            {
              String RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // expresion ::= expresion MAYOR termino 
            {
              String RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // expresion ::= expresion MENOR termino 
            {
              String RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // expresion ::= expresion OPERADOR_RESTA termino 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                String tipo_e1 = (String)e1;
                String tipo_t = (String)t;
                Symbol op_symbol = (Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1);
                
                if ((tipo_e1.equals("INT") || tipo_e1.equals("FLOAT")) && (tipo_t.equals("INT") || tipo_t.equals("FLOAT"))) {
                    RESULT = tipo_e1.equals("FLOAT") || tipo_t.equals("FLOAT") ? "FLOAT" : "INT";
                } else {
                    parser.reportarErrorSemantico("Operacion de resta invalida entre los tipos " + tipo_e1 + " y " + tipo_t, op_symbol);
                    RESULT = "error_tipo";
                }
             
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // expresion ::= expresion OPERADOR_SUMA termino 
            {
              String RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		String e1 = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                String tipo_e1 = (String)e1;
                String tipo_t = (String)t;
                Symbol op_symbol = (Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1); // Sigue usando la pila para obtener el Symbol del operador
                
                if ((tipo_e1.equals("INT") || tipo_e1.equals("FLOAT")) && (tipo_t.equals("INT") || tipo_t.equals("FLOAT"))) {
                    RESULT = tipo_e1.equals("FLOAT") || tipo_t.equals("FLOAT") ? "FLOAT" : "INT";
                } else {
                    parser.reportarErrorSemantico("Operacion de suma invalida entre los tipos " + tipo_e1 + " y " + tipo_t, op_symbol);
                    RESULT = "error_tipo";
                }
             
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("expresion",1, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // dec_var_item ::= IDENTIFICADOR ASIGNACION expresion 
            {
              VarInfo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        Symbol id_sym = (Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2);
        String tipo_e = (String) e;
        RESULT = new VarInfo(id_sym, tipo_e);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_var_item",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // dec_var_item ::= IDENTIFICADOR 
            {
              VarInfo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
        Symbol id_sym = (Symbol) CUP$Sintactico$stack.peek();
        RESULT = new VarInfo(id_sym, null);
    
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_var_item",5, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // dec_vars ::= dec_vars COMA dec_var_item 
            {
              ArrayList<VarInfo> RESULT =null;
		int lista_existenteleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int lista_existenteright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		ArrayList<VarInfo> lista_existente = (ArrayList<VarInfo>)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int itemleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int itemright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		VarInfo item = (VarInfo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                lista_existente.add(item);
                RESULT = lista_existente;
           
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_vars",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // dec_vars ::= dec_var_item 
            {
              ArrayList<VarInfo> RESULT =null;
		int itemleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int itemright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		VarInfo item = (VarInfo)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                ArrayList<VarInfo> lista = new ArrayList<>();
                lista.add(item);
                RESULT = lista;
           
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_vars",4, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // dec_variables ::= for_declaracion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("dec_variables",8, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // for_declaracion ::= tipo_dato dec_vars 
            {
              Object RESULT =null;
		int tleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int tright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		String t = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		int lista_varsleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int lista_varsright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		ArrayList<VarInfo> lista_vars = (ArrayList<VarInfo>)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
                    for (VarInfo info : lista_vars) {
                        String id = (String) info.symbol.value;
                        if (!parser.tablaSimbolos.insertar(id, t, info.symbol.left, info.symbol.right)) {
                            parser.reportarErrorSemantico("El identificador '" + id + "' ya fue declarado en este alcance", info.symbol);
                        }
                        if (info.tipoExpr != null) {
                            if (!t.equals(info.tipoExpr) && !info.tipoExpr.equals("error_tipo")) {
                                parser.reportarErrorSemantico("Tipos incompatibles. No se puede asignar " + info.tipoExpr + " a la nueva variable '" + id + "' de tipo " + t, info.symbol);
                            }
                        }
                    }
                    RESULT = lista_vars;
                 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("for_declaracion",17, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo_dato ::= VOID 
            {
              String RESULT =null;
		 RESULT = "VOID"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo_dato ::= BYTE 
            {
              String RESULT =null;
		 RESULT = "BYTE"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // tipo_dato ::= SHORT 
            {
              String RESULT =null;
		 RESULT = "SHORT"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // tipo_dato ::= DECIMAL 
            {
              String RESULT =null;
		 RESULT = "DECIMAL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // tipo_dato ::= LONG 
            {
              String RESULT =null;
		 RESULT = "LONG"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // tipo_dato ::= CHAR 
            {
              String RESULT =null;
		 RESULT = "CHAR"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // tipo_dato ::= BOOL 
            {
              String RESULT =null;
		 RESULT = "BOOL"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // tipo_dato ::= STRING 
            {
              String RESULT =null;
		 RESULT = "STRING"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // tipo_dato ::= DOUBLE 
            {
              String RESULT =null;
		 RESULT = "DOUBLE"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // tipo_dato ::= FLOAT 
            {
              String RESULT =null;
		 RESULT = "FLOAT"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // tipo_dato ::= INT 
            {
              String RESULT =null;
		 RESULT = "INT"; 
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("tipo_dato",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // asignacion ::= IDENTIFICADOR ASIGNACION expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)).value;
		int eleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).left;
		int eright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()).right;
		String e = (String)((java_cup.runtime.Symbol) CUP$Sintactico$stack.peek()).value;
		
    Symbol id_sym = (Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2);
    String tipo_e = (String) e;
    RESULT = new VarInfo(id_sym, tipo_e);

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("asignacion",16, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-2)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // sentencia ::= declaracion_metodo 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // sentencia ::= IDENTIFICADOR PAREN_APERTURA PAREN_CIERRE PUNTO_COMA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)).value;
		
                Symbol id_sym = (Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3);
                Simbolo s = parser.tablaSimbolos.buscar(id_sym.value.toString());
                if (s == null) {
                    parser.reportarErrorSemantico("La función '" + id_sym.value + "' no ha sido declarada", id_sym);
                }
           
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-3)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // sentencia ::= BREAK PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // sentencia ::= asignacion PUNTO_COMA 
            {
              Object RESULT =null;
		int aleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int aright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object a = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		
                VarInfo info = (VarInfo) a;  
                Symbol id_sym = info.symbol;
                String e = info.tipoExpr;
                Simbolo s = parser.tablaSimbolos.buscar(id_sym.value.toString());
                if (s == null) {
                    parser.reportarErrorSemantico("La variable '" + id_sym.value + "' no ha sido declarada", id_sym);
                } else if (!s.tipo.equals(e) && !e.equals("error_tipo")) {
                    parser.reportarErrorSemantico("Tipos incompatibles. No se puede asignar " + e + " a la variable '" + id_sym.value + "' de tipo " + s.tipo, id_sym);
                }
           
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // sentencia ::= sentencia_switch 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // sentencia ::= sentencia_for 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // sentencia ::= sentencia_do 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // sentencia ::= sentencia_while 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // sentencia ::= sentencia_if 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // sentencia ::= dec_variables 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencia",7, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // sentencias ::= sentencias sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencias",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // sentencias ::= sentencia 
            {
              Object RESULT =null;

              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("sentencias",6, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          return CUP$Sintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= sentencias EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)).value;
		RESULT = start_val;
              CUP$Sintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintactico$stack.elementAt(CUP$Sintactico$top-1)), ((java_cup.runtime.Symbol)CUP$Sintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintactico$parser.done_parsing();
          return CUP$Sintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

