
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 24 16:25:38 CST 2025
//----------------------------------------------------

package Act4;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHORT = 12;
  public static final int IDENTIFICADOR = 78;
  public static final int OPERADOR_RESTA = 54;
  public static final int INTERNAL = 35;
  public static final int BOOL = 2;
  public static final int OPERADOR_SUMA = 53;
  public static final int MENOR_IGUAL = 65;
  public static final int CONST = 38;
  public static final int VALOR_ENTERO = 79;
  public static final int ASYNC = 37;
  public static final int MAYOR = 62;
  public static final int CORCHETE_APERTURA = 73;
  public static final int READONLY = 43;
  public static final int DIFERENTE = 61;
  public static final int VIRTUAL = 47;
  public static final int PAREN_CIERRE = 72;
  public static final int USHORT = 16;
  public static final int DOUBLE = 6;
  public static final int OPERADOR_DIVISION = 56;
  public static final int YIELD = 31;
  public static final int PROTECTED = 34;
  public static final int FALSE = 50;
  public static final int NOT = 68;
  public static final int SBYTE = 11;
  public static final int OBJECT = 10;
  public static final int OVERRIDE = 42;
  public static final int FLOAT = 7;
  public static final int GOTO = 29;
  public static final int PUNTO_COMA = 75;
  public static final int LLAVE_CIERRE = 70;
  public static final int COMA = 76;
  public static final int ABSTRACT = 36;
  public static final int ULONG = 15;
  public static final int TRUE = 49;
  public static final int LONG = 9;
  public static final int WHILE = 23;
  public static final int DECIMAL = 5;
  public static final int CHAR = 4;
  public static final int SWITCH = 20;
  public static final int DO = 24;
  public static final int VALOR_CADENA = 51;
  public static final int FOR = 25;
  public static final int IGUAL_A = 60;
  public static final int VOID = 17;
  public static final int EXTERN = 40;
  public static final int PUBLIC = 32;
  public static final int RETURN = 30;
  public static final int PAREN_APERTURA = 71;
  public static final int ELSE = 19;
  public static final int MENOR = 63;
  public static final int BREAK = 27;
  public static final int INT = 8;
  public static final int EOF = 0;
  public static final int PUNTO = 77;
  public static final int DEFAULT = 22;
  public static final int SEALED = 44;
  public static final int LLAVE_APERTURA = 69;
  public static final int OR = 67;
  public static final int VALOR_FLOTANTE = 52;
  public static final int error = 1;
  public static final int CONTINUE = 28;
  public static final int IF = 18;
  public static final int UMENOS = 58;
  public static final int UINT = 14;
  public static final int FOREACH = 26;
  public static final int OPERADOR_MODULO = 57;
  public static final int VOLATILE = 48;
  public static final int ASIGNACION = 59;
  public static final int CASE = 21;
  public static final int NEW = 41;
  public static final int STRING = 13;
  public static final int BYTE = 3;
  public static final int UNSAFE = 46;
  public static final int AND = 66;
  public static final int CORCHETE_CIERRE = 74;
  public static final int PRIVATE = 33;
  public static final int STATIC = 45;
  public static final int MAYOR_IGUAL = 64;
  public static final int EVENT = 39;
  public static final int OPERADOR_MULTIPLICACION = 55;
}

